### PR TITLE
feat: add BasicAuth, fix OAuth wrongfully encoded

### LINKED ISSUE #33: GET and POST require too many auth parameters
### Expected Behavior

If you're using basic auth you do not need clientID and clientSecret. Likewise, if you're using clientID and secret you do not need username and password. 

### Actual Behaviour

Kestra requires all 4 parameters

### Steps To Reproduce

using servicenow dev account
```   
  - id: http
    type: io.kestra.plugin.core.http.Request
    uri: https://dev123.service-now.com/api/now/table/incident
    options:
      basicAuthUser: annabelle.coger
      basicAuthPassword: mypass
  - id: service
    type: io.kestra.plugin.servicenow.Get
    username: annabelle.coger
    password: mypass
    domain: dev123
    table: incident
```

### Environment Information

- Kestra Version: 0.22-rc1
- Plugin version: 0.22-rc1
- Operating System (OS / Docker / Kubernetes): Docker

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by AcevedoR**
- fixes #33

### CODE REVIEW

File: src/main/java/io/kestra/plugin/servicenow/AbstractServiceNow.java [hunk 1]
```diff
@@ -49,19 +44,17 @@ public abstract class AbstractServiceNow extends Task  {
     private Property<String> domain;
 
     @NotNull
-    @Schema(title = "ServiceNow username.")
+    @Schema(title = "ServiceNow username.", description = "to be used with 'password' for a BasicAuth authentication")
     private Property<String> username;
 
     @NotNull
```
Comment (brian-mulier-p) [inline src/main/java/io/kestra/plugin/servicenow/AbstractServiceNow.java:50]: NotNull should be removed also on both username and password I think as if I understood the issue, you can also use clientId and clientSecret without username / password?

If so I think you should add a validator to check if username and password are filled OR clientId & clientSecret are filled because with @NotNull you won't be able to do that I think

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]

File: src/main/java/io/kestra/plugin/servicenow/AbstractServiceNow.java (hunk 1 above)
Comment (AcevedoR) [reply src/main/java/io/kestra/plugin/servicenow/AbstractServiceNow.java:50]: > NotNull should be removed also on both username and password I think as if I understood the issue, you can also use clientId and clientSecret without username / password?
actually no, for OAuth you have to send all 4

Comment (brian-mulier-p) [reply src/main/java/io/kestra/plugin/servicenow/AbstractServiceNow.java:50]: Also might be worth to add the micronaut-validation library in tests to add a test to verify that

**Review by brian-mulier-p — APPROVED** [review]
